### ISSUE TITLE
Segmentation Fault and Unclear Functions/Actions

### ISSUE THREAD

**Issue by TRianR** [jlagaman/CSCI2270-card-lib#1]
Your program segmentation faults when I to draw a card from the deck before I shuffle the deck. Same for if I shuffle the deck, draw a few cards, then reset the deck; I have to shuffle the deck before I draw or it seg faults. After the shuffling of the deck the program runs fine however. 
A little more information in the menu, or right as you call the function, would be helpful. The replaceCard function specifically is a little confusing when looked at via the printed menu. First looks seemed that it would replace a card in the deck with another card but when clicked it seems to do nothing at all. When looked at in the code it seems that it inserts the last drawn card back into the deck. So a little clarification on what it's doing would be less confusing,  like a cout statement saying that it replaced the card back into the deck or something.
Quickly pulled it off github and it ran the first time after putting it in a project folder so it's runs good.

**Comment by dtrahan41** [comment]
Thanks mate! I think I solved it.
